const jobs = [
  {
    id: 1,
    date: "20 June 2024",
    company: "Amazon",
    title: "Senior UI/UX Designer",
    rate: 30,
    location: "San Francisco, CA",
    workType: "part-time",
    experienceLevel: "senior level",
    jobType: "remote",
    duration: "temporarily",
  },
  {
    id: 2,
    date: "15 June 2024",
    company: "Google",
    title: "Software Engineer",
    rate: 45,
    location: "Mountain View, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "temporarily",
  },
  {
    id: 3,
    date: "10 June 2024",
    company: "Microsoft",
    title: "Product Manager",
    rate: 50,
    location: "Redmond, WA",
    workType: "full-time",
    experienceLevel: "senior level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 4,
    date: "05 June 2024",
    company: "Facebook",
    title: "Data Scientist",
    rate: 55,
    location: "Menlo Park, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 5,
    date: "01 June 2024",
    company: "Apple",
    title: "Hardware Engineer",
    rate: 60,
    location: "Cupertino, CA",
    workType: "full-time",
    experienceLevel: "senior level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 6,
    date: "25 May 2024",
    company: "Netflix",
    title: "DevOps Engineer",
    rate: 40,
    location: "Los Gatos, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 7,
    date: "20 May 2024",
    company: "Airbnb",
    title: "Marketing Manager",
    rate: 35,
    location: "San Francisco, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 8,
    date: "15 May 2024",
    company: "Uber",
    title: "Operations Manager",
    rate: 38,
    location: "San Francisco, CA",
    workType: "full-time",
    experienceLevel: "senior level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 9,
    date: "10 May 2024",
    company: "Spotify",
    title: "Creative Director",
    rate: 45,
    location: "New York, NY",
    workType: "full-time",
    experienceLevel: "senior level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 10,
    date: "05 May 2024",
    company: "Adobe",
    title: "Graphic Designer",
    rate: 25,
    location: "San Jose, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 11,
    date: "01 May 2024",
    company: "Salesforce",
    title: "Business Analyst",
    rate: 30,
    location: "San Francisco, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 12,
    date: "25 April 2024",
    company: "IBM",
    title: "Research Scientist",
    rate: 50,
    location: "Armonk, NY",
    workType: "full-time",
    experienceLevel: "senior level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 13,
    date: "20 April 2024",
    company: "Intel",
    title: "Embedded Software Engineer",
    rate: 45,
    location: "Santa Clara, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 14,
    date: "15 April 2024",
    company: "LinkedIn",
    title: "Content Strategist",
    rate: 35,
    location: "Sunnyvale, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 15,
    date: "10 April 2024",
    company: "Twitter",
    title: "Community Manager",
    rate: 30,
    location: "San Francisco, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 16,
    date: "05 April 2024",
    company: "Snapchat",
    title: "Mobile Developer",
    rate: 40,
    location: "Venice, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 17,
    date: "01 April 2024",
    company: "Pinterest",
    title: "Frontend Developer",
    rate: 35,
    location: "San Francisco, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 18,
    date: "25 March 2024",
    company: "Tesla",
    title: "Battery Engineer",
    rate: 50,
    location: "Palo Alto, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 19,
    date: "20 March 2024",
    company: "SpaceX",
    title: "Aerospace Engineer",
    rate: 60,
    location: "Hawthorne, CA",
    workType: "full-time",
    experienceLevel: "senior level",
    jobType: "on-site",
    duration: "permanent",
  },
  {
    id: 20,
    date: "15 March 2024",
    company: "Slack",
    title: "Customer Support Specialist",
    rate: 25,
    location: "San Francisco, CA",
    workType: "full-time",
    experienceLevel: "entry level",
    jobType: "remote",
    duration: "permanent",
  },
  {
    id: 21,
    date: "10 March 2024",
    company: "Stripe",
    title: "Backend Developer",
    rate: 45,
    location: "San Francisco, CA",
    workType: "full-time",
    experienceLevel: "mid level",
    jobType: "on-site",
    duration: "permanent",
  },
];

export default jobs;
